      SUBROUTINE DOOT(IA,RPRM,NRWK,BB,IC)
        !DEC$ ATTRIBUTES DLLEXPORT :: DOOT      
       !DEC$ ATTRIBUTES STDCALL,ALIAS:'DOOT':: DOOT
       !DEC$ ATTRIBUTES REFERENCE::IA,RPRM,NRWK,BB,IC
      
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION RPRM(*),BB(*)
      CALL DOT001 (RPRM,NRWK)
         IF(RPRM(3).GT.1.0E-20) RPRM(3)=3.0
         IF(RPRM(12).GT.1.0E-20) RPRM(12)=4.0
      RETURN
      END
      
      SUBROUTINE DOT001 (RPRM,NRWK)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION RPRM(*)
      DO 10 I=1,NRWK
         IF(ABS(RPRM(I)).LT.1.0E-20) RPRM(I)=1.0
10    CONTINUE
      IF(RPRM(2).GT.1.0E-6) RPRM(2)=1.0E-6
      RETURN
      END