      SUBROUTINE DOT(NCON,MINMAX,NRWK,
     1NRIWK,OBJ,X,XL,XU,G,RPRM,IPRM,WK,IWK)
       !DEC$ ATTRIBUTES DLLEXPORT :: DOT      
       !DEC$ ATTRIBUTES STDCALL,ALIAS:'DOT'::DOT
       !DEC$ ATTRIBUTES REFERENCE::OBJ,X,XL,XU,G,RPRM,IPRM,WK,IWK
       !DEC$ ATTRIBUTES VALUE::NCON,MINMAX,NRWK,NRIWK
C
C                 ***** (C) COPYRIGHT *****
C     ***** VANDERPLAATS RESEARCH & DEVELOPMENT, INC. *****
C         ***** ALL RIGHTS RESERVED, WORLDWIDE *****
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION X(*),XL(*),XU(*),G(*),RPRM(*),IPRM(*),WK(*),
     1IWK(*),IPOINT(40),DUMMY(1)
       DO 10 I=1,20
          RPRM(I)=1.0
10      IPRM(I)=1
      RETURN
      END